services:
  dev-db:
    image: postgres:16
    ports:
      - 5433:5432 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: nest
    volumes:
      - /c/Users/thsib/Documents/NestJS/pg_data:/var/lib/postgresql/data
    networks:
      - pg-network

  test-db:
    image: postgres:16
    ports:
      - 5434:5432 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: nest
    networks:
      - pg-network

networks:
  pg-network:
