"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var passport_1 = require("@nestjs/passport");
var console_1 = require("console");
var passport_jwt_1 = require("passport-jwt");
(0, console_1.log)(passport_1.PassportStrategy);
(0, console_1.log)(passport_jwt_1.Strategy);
(0, console_1.log)((0, passport_1.PassportStrategy)(passport_jwt_1.Strategy));
(0, console_1.log)(passport_1.PassportStrategy);
(0, console_1.log)(passport_jwt_1.Strategy);
(0, console_1.log)((0, passport_1.PassportStrategy)(passport_jwt_1.Strategy));
